project:
  type: website
  output-dir: docs

website:
  title: "Adelaide Dahl"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - pathfinding.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full 

editor: visual

