---
title: "Teaching Philosophy"
---

<h2 class="center-text">My story in learning</h2>

During the COVID-19 pandemic, I realized that I missed learning. Not just sitting in class and engaging with material but really *absorbing* and *engaging* with the topics and content I was presented with in my courses. In the age of zoom univeristy, I sought out opportunities to learn outside of the classroom and discovered the topics I was most excited about were also those for which I felt the most passionate - ocean science and art.

Since then, I have worked towards helping students K-12 find their passion for learning. I started by leaning on my strengths in science and art to develop curricula and educational pathways, eventually engaging with students from around the world to help them identify their strengths and bolster their personal journey in education.

<h2 class="center-text">How can I help?</h2>

I am here to work with your student to design a learning pathway that works best for them. Whether for executive functioning or college essay writing, I'm here to work with you to find and utilize each student's superpowers while continuing to grow their interests, strengths and new skill development.

<h3 class="orange-text"> Contact Me </h3>

<p> Feel free to reach out if you are interested in working with me or have any questions! </p>

<a href="mailto:adelaidedahl@ucsb.edu?subject=Tutoring Inquiry" class="email-button">Click to Email</a>
